

pipeline {
     agent {
        docker { image 'node:16.13.1-alpine' }
    } 
    stages {
        stage('Build') { 
            steps {
                sh "npm install"
                sh "npm run build"
            }
        }
        stage('Deploy') { 
            steps {
                echo "Deploy"
            }
        }
    }
}